package exception;

import java.util.Scanner;

public class excep1 {
	/*public void calculator(int a,int b) {
		try {
		int add=a+b;
		int sub=a-b;
		int mul=a*b;
		int div=a/b;
		System.out.println(add);
		System.out.println(sub);
		System.out.println(mul);
		System.out.println(div);
		
		int x[]=new int[6];
		x[15]=25;
		System.out.println(x[15]);
		
		}catch(ArithmeticException e)
		{
			System.out.println("Exception!!!");
		}
		finally
		{
			System.out.println("anyways, did u enjoy?! LOL!");
		}
		
	}*/
	public void method2() throws Exception
	{
		Scanner sc=new Scanner(System.in);
		int s;
		s=sc.nextInt();
		System.out.println(s);
		
	}
	

}
